import type { PortfolioData } from './portfolio.models';

export const FALLBACK_PORTFOLIO_DATA: PortfolioData = {
  fetchedAt: 0,
  technologies: [
    { name: 'Python', source: 'curated', projectCount: 2 },
    { name: 'Flutter', source: 'curated', projectCount: 1 },
    { name: 'Firebase', source: 'curated', projectCount: 1 },
    { name: 'React', source: 'curated', projectCount: 1 },
    { name: 'Django', source: 'curated', projectCount: 1 },
    { name: 'Docker', source: 'curated', projectCount: 1 },
    { name: 'TensorFlow', source: 'curated', projectCount: 1 },
    { name: 'Scikit-learn', source: 'curated', projectCount: 1 },
    { name: 'JavaScript', source: 'curated', projectCount: 1 },
    { name: 'TypeScript', source: 'curated', projectCount: 1 },
    { name: 'Node.js', source: 'curated', projectCount: 1 },
    { name: 'PostgreSQL', source: 'curated', projectCount: 1 },
  ],
  projects: [
    {
      id: 1,
      name: 'university-timetable-companion-app',
      displayName: 'Uni Timetable Companion',
      description:
        'An app to manage Weekly Recurring Time Tables for Universities — hall availability checking, seminar & subject management, and personal task management.',
      htmlUrl: 'https://github.com/melanga/university-timetable-companion-app',
      homepageUrl: null,
      primaryLanguage: 'Dart',
      technologies: ['Flutter', 'Firebase', 'Cloud Firestore', 'Dart'],
      topics: ['flutter', 'firebase'],
      stars: 0,
      forks: 0,
      updatedAt: '2022-01-01T00:00:00Z',
      isFork: false,
      isArchived: false,
      languageBreakdown: new Map([['Dart', 100]]),
    },
    {
      id: 2,
      name: 'event-portal',
      displayName: 'Event Portal',
      description:
        'Web portal for event service providers & customers with location and rating-based searching and integrated real-time chat.',
      htmlUrl: 'https://github.com/melanga/event-portal',
      homepageUrl: null,
      primaryLanguage: 'JavaScript',
      technologies: ['PostgreSQL', 'Express', 'React', 'Node.js', 'Redux', 'Socket.io'],
      topics: ['pern-stack', 'socket.io'],
      stars: 0,
      forks: 0,
      updatedAt: '2022-06-01T00:00:00Z',
      isFork: false,
      isArchived: false,
      languageBreakdown: new Map([
        ['JavaScript', 85],
        ['CSS', 10],
        ['HTML', 5],
      ]),
    },
    {
      id: 3,
      name: 'GroupMeetPlanner',
      displayName: 'Group Meet Planner',
      description:
        'Web application that helps users create groups and find meeting times that work for every member.',
      htmlUrl: 'https://github.com/melanga/GroupMeetPlanner',
      homepageUrl: null,
      primaryLanguage: 'Python',
      technologies: ['Django', 'SQLite', 'Docker', 'Python'],
      topics: ['django', 'docker'],
      stars: 0,
      forks: 0,
      updatedAt: '2022-09-01T00:00:00Z',
      isFork: false,
      isArchived: false,
      languageBreakdown: new Map([
        ['Python', 80],
        ['HTML', 15],
        ['CSS', 5],
      ]),
    },
  ],
};
